[package]
name = "n-nacos-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
colored = { workspace = true }
clap = { workspace = true }
rust-ini = { workspace = true }
sled = { workspace = true }
actix-web = { workspace = true }
tonic = { workspace = true }
utils = { path = "../../commons/utils"}
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }